#!/usr/bin/env python
#coding: utf-8

'''
 MATEMÁTICAS DISCRETAS
 Ejercicio: 1000 - 9999.
 * Nombre: Viviana Marcela Peña Márquez. 
 * Programa: Matemáticas.
 * Fecha: Martes, 27 de enero de 2015.
 * Institución: Konrad Lorenz Fundación Universitaria.
 * Profesor: Óscar Gómez.

Enunciado:
¿Cuántos números hay del 1000 al 9999 que tengan cifras diferentes en orden creciente o decreciente? 
'''

a=[]
b=[] 

for i in range(1000,10000):
    l=i
    for j in range (0,4):
    	a.append(i%10)
    	i=i/10
    a.reverse()
    if(a[0]<a[1] and a[1]<a[2] and a[2]<a[3]):
    	b.append(l)
    if(a[0]>a[1] and a[1]>a[ 2] and a[2]>a[3]):
    	b.append(l)  
    #print a
    a = []	
    
for m in range(len(b)):
	print b[m]
	
#print b
print "\nSon: ",len(b)
