#!/usr/bin/env python
#coding: utf-8

'''
 MATEMÁTICAS DISCRETAS
 Ejercicio: Combinación Lineal (Por Fuerza Bruta).
 * Nombre: Viviana Marcela Peña Márquez. 
 * Programa: Matemáticas.
 * Fecha: Martes,12 de mayo de 2015.
 * Institución: Konrad Lorenz Fundación Universitaria.
 * Profesor: Óscar Gómez.
'''

b = input("Número mayor = ")
a = input("Número menor = ")

bc = b
ac = a

r = 1 

while (r>0):
	r=b%a
	b=a
	a=r	

#El máximo común divisor
#print b

print ""
print "El mcd (",bc,",",ac,") es:",b
print ""

for i in range (-1000,1001):
	for j in range (-1000,1001):
		if((bc*i+ac*j)==b):
			#print i,j
			print b,"=",bc,"(",i,") +",ac,"(",j,")"
			
print ""
