#!/usr/bin/env python
#coding: utf-8

'''

 MATEMÁTICAS DISCRETAS
 Ejercicio: Factorial
 * Nombre: Viviana Marcela Peña Márquez. 
 * Programa: Matemáticas.
 * Fecha: Martes, 17 de febrero de 2015.
 * Institución: Konrad Lorenz Fundación Universitaria.
 * Profesor: Óscar Gómez.

'''

def factorial(n):
	f = 1
	for i in range (1,n+1):
		f = f*i
	return f
	
print factorial(7)

def nPr(n,r):
	f = 1 
	for i in range (n-(r-1),n+1):
		f = f*i
	return f
	
print nPr(10,4)

def nCr(n,r):
	return nPr(n,r)/factorial(r)
	
print nCr(10,0)
