#!/usr/bin/env python
#coding: utf-8

'''

 MATEMÁTICAS DISCRETAS
 Ejercicio: Fibonacci
 * Nombre: Viviana Marcela Peña Márquez. 
 * Programa: Matemáticas.
 * Fecha: Martes, 24 de febrero de 2015.
 * Institución: Konrad Lorenz Fundación Universitaria.
 * Profesor: Óscar Gómez.

'''

#no recursivo
'''
n = int(input("Enter a number: "))

first=second=1

if(n==0 or n==1):
	print 1
	
else:
	for i in range (1,n):
		first = first + second
		second = first - second
	
print first
'''

#recursivo

n = int(input("Enter a number: "))

def fibrec(n):
	#print n
	if(n==0 or n==1):
		return 1
	else:
		#print 'n: ',n,' ',fibrec(n-1),'+',fibrec(n-2),'=',fibrec(n-1)+fibrec(n-2)
		return fibrec(n-1)+fibrec(n-2)

print fibrec(n)

	
