#!/usr/bin/env python
#coding: utf-8

'''

 MATEMÁTICAS DISCRETAS
 Ejercicio: Laura Recursivo
 * Nombre: Viviana Marcela Peña Márquez. 
 * Programa: Matemáticas.
 * Fecha: Martes, 24 de febrero de 2015.
 * Institución: Konrad Lorenz Fundación Universitaria.
 * Profesor: Óscar Gómez.

'''


#global cont
#cont = 0

def laurarec (x,y):
	global cont
	cont = 0
	if (x==3 and y==3):
		cont = cont+1
	else:
		if(y<3):
			laurarec(x,y+1)
			cont = cont+1
		if(x<3):
			laurarec(x+1,y)
			cont = cont+1
	return cont

#laurarec(3,3)

print laurarec(1,1)
print cont
