#!/usr/bin/env python
#coding: utf-8

'''
 MATEMÁTICAS DISCRETAS
 Ejercicio: De una base a 10.
 * Nombre: Viviana Marcela Peña Márquez. 
 * Programa: Matemáticas.
 * Fecha: Martes, 7 de abril de 2015.
 * Institución: Konrad Lorenz Fundación Universitaria.
 * Profesor: Óscar Gómez.
'''

import numpy as np
import math

n = input("Dígite un número (cádena) n = ")
b = input("Base = ")

n=n[::-1]

#print n
#print len(n)

s=0

for j in range (0,len(n)):
	if(ord(n[j])>=48 and ord(n[j])<=57):
		s=s+(ord(n[j])-48)*(math.pow(b,j))
	else:
		if(ord(n[j])>=65 and ord(n[j])<=90):
			s=s+(ord(n[j])-55)*(math.pow(b,j))
	
print s
