#!/usr/bin/env python
#coding: utf-8

'''
 MATEMÁTICAS DISCRETAS
 Ejercicio: Organizar un vector.
 * Nombre: Viviana Marcela Peña Márquez. 
 * Programa: Matemáticas.
 * Fecha: Martes, 10 de febrero de 2015.
 * Institución: Konrad Lorenz Fundación Universitaria.
 * Profesor: Óscar Gómez.
'''

A=[9,3,8,1,4]

for i in range (1,len(A)):
	aux = A[i]
	j=i-1
	while(A[j]>aux and j>=0):
		A[j+1]=A[j]
		j=j-1		
	A[j+1]=aux
	
print A
